# Generated by Django 5.1.7 on 2025-03-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(default='Tegnologia', max_length=20),
        ),
        migrations.AddField(
            model_name='noticia',
            name='ciudad',
            field=models.CharField(default='Riohacha', max_length=20),
        ),
    ]
